### PR TITLE
Fixes/UI fixes

### LINKED ISSUE #219: Scan QR to get an address hangs
**Bug Description**
Using camera to scan QR code for the address keeps hanging once address was scanned. 
This happens for both transfers.

**Steps to Reproduce**
Select send and  scan QR.
Select send shielded and scan QR.

**Expected Result**
Once address was recognized, application should change the view back to the view for sending CCDs. Address should be inserted into the address field and transfer can be carried out.
Same result is expected for shielded transfers.

**Actual Result**
After QR code was scanned, it seems that application keeps hanging. It is possible to select back and address would be there but it seems that address is not valid while it matches the one that was scanned.

Video
https://user-images.githubusercontent.com/98821384/157415735-c95b50df-1da0-4087-9223-edc0973b9b8b.mp4

**Versions**
- Software Version: Testnet 2.0.0 (36)
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

### LINKED ISSUE #220: Toggle should be "pressed down" when the tab is selected
**Bug Description**
Selected tab is highlighted while it should be grayed (pressed down) when the tab is active.
This should be teh same as implemented on Android version 2.0.1 (71)

**Steps to Reproduce**
Show shielded balance.

**Expected Result**
Shielded balance view should appear and the tab should look as it was pressed down. It should look the same as on Android MW.

**Actual Result**
It looks the opposite compared to implementation on Android MW.

Image:
toggling

**Versions**
- Software Version: Testnet 2.0.35
- OS: iOS 14.8
- Browser: N/A
- Mobile device: iPhone SE

### LINKED ISSUE #224: Wrong heading
**Bug Description**
IMG_5969
IMG_5970

**Steps to Reproduce**

**Expected Result**
"The shielded transfer" as heading.

**Actual Result**
"The shielding transaction"

**Versions**
- Software Version 2.0.0 (36)
- iOS 15.1
- iPhone 11

### PR DESCRIPTION
**Pull request by ruxandra-constantinescu**
## Purpose

Fixes #219
Fixes #224
Fixes #220 and #228  (same underlying issue)

## Changes

Updated heading text
We now remove the childCoordinators for AccountDetails coordinator as we would in a stack, from back to front instead of removing all of them
Fixes issue with shielded balance not showing decrypt and not updating to shielded transactions
Fixed needing to press the send button twice after QR scanning 

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

### CODE REVIEW

File: ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift [hunk 1]
```diff
@@ -133,8 +133,10 @@ extension AccountDetailsPresenter: AccountDetailsPresenterProtocol {
         account = account.withShowShielded(shouldShow)
         if shouldShow {
             switchToBalanceType(.shielded)
+            userSelectedTransfers()
```
Comment (kristiyandobrev) [inline ConcordiumWallet/Views/AccountsView/AccountDetails/AccountDetailsPresenter.swift:136]: Could be called only once after the `if/else` statement

**Review by kristiyandobrev — APPROVED** [review]
Looks good. Minor comment only :)
