### PR TITLE
Accounts identity cleanup

### LINKED ISSUE #24: Black camera view after denying permission
**Bug Description**
A completely black camera view is shown when you deny the request to use the camera.
The app should check whether the camera is enabled and never show the black camera view.
NB: Users can manually enable the camera permissions in Settings > Concordium

**Steps to Reproduce**
1. Install the wallet
2. When creating an identity, the app will ask for permission to use the camera: click 'Don't allow'
3. Try to take a photo of your id document

**Expected Result**
The app will tell you that it is not possible to create an identity without the use of a camera and prompt you for permissions again.

**Actual Result**
The camera opens up, but everything is black:

**Versions**
- Software Version: 10.0.14 (testnet), 1.0.4 (mainnet)
- OS: 14.6
- Browser: Safari / Brave Browser (not sure which one is used when a webpage is loaded within an app)
- Mobile device, if applicable: iPhone 11 Pro

### PR DESCRIPTION
**Pull request by kristiyandobrev**
## Purpose

* Collect all cleanup funcs in `StorageManager`
* Cleanup accounts without address upon login*
* Bump project version (18)

_* That will cover the scenario when the user changes a permission from the `Settings` app and the iOS restarts the app. Unfortunately iOS does not provide us with such a system event and the best we can do is to basically cleanup the accounts without address upon login_

Closes #24

### CODE REVIEW

File: ConcordiumWallet/Service/StorageManager.swift [hunk 1]
```diff
@@ -373,4 +377,38 @@ class StorageManager: StorageManagerProtocol {
...
+    func removeUnfinishedIdentities() {
+        let unfinishedIdentities = getIdentities().filter { $0.ipStatusUrl.isEmpty }
+        for identity in unfinishedIdentities {
+            removeIdentity(identity)
+        }
+    }
+    
+    func removeUnfinishedAccounts() {
+        guard
+            let unfinishedAccount = getAccounts().first(where: { $0.identity == nil || $0.identity?.ipStatusUrl == nil || $0.identity?.state == .failed })
```
Comment (abizjak) [inline ConcordiumWallet/Service/StorageManager.swift:390]: Why only remove the first account? The function name indicates it should remove all unfinished accounts.

File: ConcordiumWallet/Service/StorageManager.swift [hunk 2]
```diff
@@ -373,4 +377,38 @@ class StorageManager: StorageManagerProtocol {
             realm.delete(transferEntity)
         }
     }
+    
+    func removeUnfinishedIdentities() {
+        let unfinishedIdentities = getIdentities().filter { $0.ipStatusUrl.isEmpty }
```
Comment (abizjak) [inline ConcordiumWallet/Service/StorageManager.swift:382]: Are failed identities removed elsewhere?

File: ConcordiumWallet/Service/StorageManager.swift (hunk 1 above)
Comment (kristiyandobrev) [reply ConcordiumWallet/Service/StorageManager.swift:390]: There has been no change in that since our last discussion in [here](https://github.com/Concordium/concordium-reference-wallet-ios/pull/44). In this PR the functions for cleaning up accounts and identities were only moved to another more centeralized place - `StorageManager`

Comment (abizjak) [reply ConcordiumWallet/Service/StorageManager.swift:390]: Ok.

**Review by abizjak — APPROVED** [review]
Ok, since this is just refactoring.

I am still not sure about the entire handling, but this PR does not seem to introduce any observable change.

**Comment by kristiyandobrev** [comment]
> Ok, since this is just refactoring.
> 
> I am still not sure about the entire handling, but this PR does not seem to introduce any observable change.

It does in [here](ConcordiumWallet/AppCoordinator.swift) actually. As the description above says "Cleanup accounts without address upon login"
