### PR TITLE
Multiple identity providers support

### LINKED ISSUE #87: Support for more identity providers
**Task description**
Add support for another identity provider.

**Sub-tasks**
- [ ] change hardcoded contact info in support dialog when id fails (wallet-proxy)
- [ ] potential changes to id flow?

### PR DESCRIPTION
**Pull request by ruxandra-constantinescu**
## Purpose

Fixes #87 

## Changes

- Saved support email for each IP retrieved from the server in Realm DB and added it to the export
- Removed hardcoded values for Notabene support
- Updated localizations to use dynamic values for IP name and IP support email
- Bumped realm schema version

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

### CODE REVIEW

File: ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift [hunk 1]
```diff
@@ -8,10 +8,13 @@ import Foundation
 // MARK: - CommitmentsRandomness
 struct CommitmentsRandomness: Codable {
     let attributesRand: [String: String]
-    let credCounterRand: String
-    let idCredSecRand: String
-    let maxAccountsRand: String
-    let prfRand: String
+    let credCounterRand, idCredSECRand, maxAccountsRand, prfRand: String
```
Comment (td202) [inline ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift:11]: Why has `idCredSecRand` has changed to `idCredSECRand`?

File: ConcordiumWallet/Views/AccountsView/AccountsViewController.swift [hunk 2]
```diff
@@ -205,8 +205,11 @@ class AccountsViewController: BaseViewController, Storyboarded, AccountsViewProt
         .store(in: &cancellables)
     }
     
-    func showIdentityFailed(reference: String, completion: @escaping () -> Void) {
-        showIdentityFailureAlert(reference: reference, completion: completion)
+    func showIdentityFailed(identityProviderName: String, identityProviderSupport: String, reference: String, completion: @escaping () -> Void) {
```
Comment (td202) [inline ConcordiumWallet/Views/AccountsView/AccountsViewController.swift:208]: It would be good to be consistent on the choice of `identityProviderSupportEmail` vs. `identityProviderSupport`.

File: ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift (hunk 1 above)
Comment (ruxandra-constantinescu) [reply ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift:11]: This file is part of the Autogenerated folder so it should be autogenerated using the createModel.sh. I think it was either changed manually or a different version of quicktype was used. It does the same thing though, as below the idCredSecRand is mapped to the idCredSecRand

File: ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift [hunk 3]
```diff
@@ -8,10 +8,13 @@ import Foundation
...
+
+    enum CodingKeys: String, CodingKey {
+        case attributesRand, credCounterRand
+        case idCredSECRand = "idCredSecRand"
```
Comment (ruxandra-constantinescu) [inline ConcordiumWallet/Model/AutoGenerated/CommitmentsRandomness.swift:15]: idCredSECRand  mapped to IdCredSecRand

File: ConcordiumWallet/Views/AccountsView/AccountsViewController.swift (hunk 2 above)
Comment (ruxandra-constantinescu) [reply ConcordiumWallet/Views/AccountsView/AccountsViewController.swift:208]: Renamed identityProviderSupport to identityProviderSupportEmail

**Review by td202 — APPROVED** [review]
