### PR TITLE
Showing shielded Balance on main

### LINKED ISSUE #125: Transaction list is prone to UI errors
**Bug Description**

The list of transactions has started to become a bit prone to small UI errors. It would probably be good to get it cleaned up a bit. 

It's entirely certain what causes these smalls errors to happen, but once in a while they pop-up. See the attached screenshot for examples, e.g.:

- A lot of white space to the right of amounts
- Extra whitespace above dates, like "Yesterday" and "Today" in the screenshot.
- The grey line below the slightly blue area of the date field doesn't go all the way to the left.

IMG_3C69E36EE6BA-1

**Versions**
- Software Version: 1.0(26), and probably earlier versions as well.
- OS: iOS

### LINKED ISSUE #160: Hide the shielded balance
**Task description**

Most users have no use for the shielded balance, for which reason the shielded balance is too prominent in the UI, and causes more confusion than benefit. For this reason the shielded balance has to be hidden behind an option that needs to be enabled, before it's shown in the wallet. Then users who need it will be able to actively go and find it themselves, and all the rest who don't need it will not be bothered by it. 

This issue has three flows in Figma, i.e. Flow 3, Flow 5 and Flow 6. The main changes are shown in Flow 3, and then 5 and 6 has some smaller changes to finish the complete update to the wallet. All three flows contain need-to-have changes, but you will also be able to find nice-to-have changes, which will be put into separate issues. 

For information, the nice-to-haves are:
- [New styling on the "Send", "Shield", "Unshield", "Send (shielded) and "Receive" buttons.](https://github.com/Concordium/concordium-reference-wallet-ios/issues/170)
- [New flat styling of the transaction log.](https://github.com/Concordium/concordium-reference-wallet-ios/issues/171)

There are some need-to-haves from other issues, those are:
- [The redesigned account cards](https://github.com/Concordium/concordium-reference-wallet-ios/issues/86)
- [The updated navigation bar](https://github.com/Concordium/concordium-reference-wallet-ios/issues/161)
- [The updated "totals areas"](https://github.com/Concordium/concordium-reference-wallet-ios/issues/169)

Notes:
- You will be able to see a "Delegation" button in the dropdown menu. This is future work, so you can disregard that for now. 
- There will be a challenge in keeping track of new shielded transaction in the background.

### LINKED ISSUE #169: Update the "totals areas"
**Task description**

As we are going to need some changes in the totals area at the top of the account pages in related to the hiding the shielded balance in #160 and the coming delegation updates, we need to make some general updates to the totals areas.

All the changes to both the totals area of the general account page and the account specific totals area can be seen in Flow 9 in Figma. 

Each screen has a small description of the specific scenario.

Notes:
- When an account is a baker, it will say "Stake with baker 'bakerID'" in the totals area. In the future, when an account can delegate an amount, this string can be "Delegation with baker 'bakerID'". It might not matter now, so this can be disregarded for now if it makes no difference for how it's implemented.

### LINKED ISSUE #170: New button styling
**Task description**

In some of the need-to-have flows, new styling of the  "Send", "Shield", "Unshield", "Send (shielded) and "Receive" buttons can be seen. This styling change is nice to have with low-priority. 

The new styling can be seen in the screenshot below and e.g. in Flow 3 in Figma. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

image

### LINKED ISSUE #171: New flat styling of the transaction log
**Task description**

In some of the need-to-have flows a new flat style for the transaction log can be seen. This is a nice to have task with low priority. 

The new flat design can e.g. be seen in Flow 3, or in the screenshot below. 

**Important!** Please coordinate between between iOS and Android development, so these nice-to-have changes are only done, if there is time to do them on both platforms. 

image

### PR DESCRIPTION
**Pull request by ruxandra-constantinescu**
## Purpose

- Hide shielded balance - fixes #160
- Updated totals area - fixes #169
- Fixed transaction list UI errors - fixes #125
- Flat transaction log - fixes #171
- New button styling - fixes #170 

## Changes

Update the UI and logic for hiding the shielded balance, updating totals and updating the styling

## Checklist

- [ ] My code follows the style of this project.
- [ ] The code compiles without warnings.
- [ ] I have performed a self-review of the changes.
- [ ] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [ ] I accept the above linked CLA.

### CODE REVIEW

File: ioscommon/Commons/UIView+Additions.swift [hunk 1]
```diff
@@ -43,4 +43,14 @@ extension UIView {
             }
         )
     }
+    var isHiddenInStackView: Bool {
```
Comment (kristiyandobrev) [inline ioscommon/Commons/UIView+Additions.swift:46]: What is the difference between this property and using `isHidden` ?

Comment (ruxandra-constantinescu) [reply ioscommon/Commons/UIView+Additions.swift:46]: If you set isHidden = true on a view and then set it again to true, it will trigger some weird animations. The isHiddenInStackView only sets the isHidden to a value only if the current value is different. In this way, weird animations are avoided.

Comment (kristiyandobrev) [reply ioscommon/Commons/UIView+Additions.swift:46]: Alright. I would then suggest implicating that this is the case only when used in `StackView`'s context by putting it in `StackView` extension.

Comment (ruxandra-constantinescu) [reply ioscommon/Commons/UIView+Additions.swift:46]: It is for the views that are added in the stackview so it has to be on UIView

Comment (kristiyandobrev) [reply ioscommon/Commons/UIView+Additions.swift:46]: You can still perform the same checks on the `UIView` object within `UIStackView`: 

```
extension UIStackView { 
    func setSubview(_ view: UIView, hidden: Bool) { 
        if hidden && !view.isHidden { 
            view.isHidden = true
        } else if !hidden && view.isHidden { 
            view.isHidden= false
        }
    }
}
```
